# Generated by Django 4.0.3 on 2022-03-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_cart_ordered_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='produit',
            new_name='product',
        ),
    ]
